name: ManuallyConverterAllGuides
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch pushed to'     
        required: true
        default: 'refs/heads/qa'
        
jobs:

  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Any prerequisite steps
    - uses: actions/checkout@master
    
    - id: set-matrix
      run: |
        TASKS=$(echo $(cat $GITHUB_WORKSPACE/.github/workflows/guides.json))
        TASKS="${TASKS//'%'/'%25'}"
        TASKS="${TASKS//$'\n'/'%0A'}"
        TASKS="${TASKS//$'\r'/'%0D'}"
        echo "::set-output name=matrix::$TASKS"
 
  convertStaging:
    needs: matrix
    name: Make PR to Staging
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        guides: ${{fromJson(needs.matrix.outputs.matrix)}}
    if: contains(github.event.inputs.branch, 'qa') || contains(github.event.inputs.branch, 'staging')

    steps:
      # Any prerequisite steps

      - uses: actions/checkout@master

      - name: Checkout Cloud-hosted-guides repo
        uses: actions/checkout@v2
        with:
          ref: staging
          repository: jakub-pomykala/cloud-hosted-guides
          path: guides 

      - name: Checkout guide repo
        uses: actions/checkout@v2
        with:
          ref: qa
          repository: OpenLiberty/${{matrix.guides.guide}}
          path: guides/${{matrix.guides.guide}}

      - name: Checkout guides-common repo
        uses: actions/checkout@v2
        with:
          repository: OpenLiberty/guides-common
          path: guides/Guides-common

      - uses: actions/setup-java@v1
        with:
          java-version: "15" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Run Converter
        run: |
          branchName=${{ github.event.inputs.branch }}
          mv src guides
          mv loopReplacements.properties guides
          mv replacements.properties guides
          mv pom.xml guides
          git init
          cd guides
          mkdir -p instructions/cloud-hosted-${{matrix.guides.guide}}/
          rm -f instructions/cloud-hosted-${{matrix.guides.guide}}/README.md
          mvn compiler:compile
          mvn exec:java -Dexec.args="${{matrix.guides.guide}} ${branchName:11}"
          rm -f importFunctions.class
          rm -f functions.class
          rm -f CloudHostedGuideConverter.class
          rm -rf src
          rm -f loopReplacements.properties
          rm -f pom.xml
          rm -f replacements.properties
          mv ${{matrix.guides.guide}}.md instructions/cloud-hosted-${{matrix.guides.guide}}/instructions.md
          git config --global user.email "jakub.pomykala@hotmail.co.uk"
          git config --global user.name "jakub-pomykala"
          git add .
          git commit -m "Updated by github actions from ALL Guides"
          git checkout --ours instructions/cloud-hosted-${{matrix.guides.guide}}/instructions.md

      - uses: peter-evans/create-pull-request@v3
        with:
          title: "To Staging: Change to ${{matrix.guides.guide}}"
          token: ${{ secrets.GUIDECONVERSIONTOOL_PASSWORD }}
          push-to: jakub-pomykala/cloud-hosted-guides
          body: "Updated by github actions, triggered by the MANUAL ACTION"
          branch: "cloud-hosted-${{matrix.guides.guide}}/staging"
          base: "staging"
          # labels: "RunTests"
        name: Create Pull Request